# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9752b1eab84c4c527c7e443bda519a7435bb2e6b27e040f46ee98c1ea4f0e3c901f2e65ea3d0113154cadf664dfb0aa3a963941abfbf66f09ea1b736bdb04b0

test:
  secret_key_base: 9bb29f219daa32b5bc7f5557b4dfe5661d009cedd45676c855c6b7f2ed465ea4f94a0d3da907e999652e7232bbdfa117b2fc0e040061990a4f71f1a4b28066e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
